from __future__ import annotations
from ._legacy_support import (
    HYDRATION_SLOT_META,
    _get_due_and_upcoming_prompt,
    _sync_goal_based_hydration_prompts,
    _missed_hydration_summary,
    _hydration_goal_plan,
    _hydration_schedule_rows,
    _normalize_beverage,
    _serialize_prompt,
    _sleep_reminder_payload,
    _hydration_prompt_label,
    _increment_water_if_within_limit,
    _water_limit_error,
    _default_hydration_schedule_map,
    _ensure_hydration_schedule_defaults,
    _get_or_create_log_for_date,
    _get_or_create_log_for_today,
    _infer_beverage_from_text,
    _sync_meal_task_completion,
    _update_log_meal_insight,
)
