from __future__ import annotations

APP_TIMEZONE = "America/Los_Angeles"
UTC_TIMEZONE = "UTC"

GLASS_VOLUME_ML = 250
MAX_SINGLE_WATER_ML = 2000
MAX_DAILY_WATER_ML = 8000
HYDRATION_DUE_GRACE_MINUTES = 75
HYDRATION_EXTRA_MIN_GAP_MINUTES = 45
EYE_EXERCISE_THRESHOLD_MINUTES = 25
DEFAULT_POMODORO_FOCUS_MINUTES = 25
DEFAULT_POMODORO_BREAK_MINUTES = 5
DEFAULT_POMODORO_ACTIVITY_LABEL = "work"

AI_MAX_MESSAGE_CHARS = 1200
WELLNESS_BLEND_FACTOR = 0.12

TASK_ROLLOVER_MAX_PER_DAY = 12
ACTIVITY_ENTRY_RETENTION_DAYS = 180
ACTIVITY_ENTRY_MAX_ROWS = 1000
ACTIVITY_PRUNE_INTERVAL_HOURS = 6
CLIENT_STATE_RETENTION_DAYS = 3
AI_INTERVENTION_HISTORY_DAYS = 45

MINIMUM_AI_WATER_GOAL_ML = 1200

LOG_MAX_BYTES = 1_000_000
LOG_BACKUP_COUNT = 3
DEFAULT_LOG_LEVEL = "INFO"

HISTORY_PAGE_SIZE = 20
POMODORO_STATE_CLIENT_KEY = "pomodoro_active_state"
POMODORO_STATE_MAX_AGE_DAYS = 7
OPENAI_DEFAULT_MODEL = "gpt-4o-mini"
OPENAI_MODEL_FALLBACKS = ("gpt-4.1-mini", "gpt-4o")
